<?php

/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

namespace CustomerManagementFrameworkBundle\Encryption;

use CustomerManagementFrameworkBundle\Traits\LoggerAware;
use Defuse\Crypto\Crypto;
use Defuse\Crypto\Encoding;
use Defuse\Crypto\Exception\BadFormatException;
use Defuse\Crypto\Key;

class DefaultEncryptionService implements EncryptionServiceInterface
{
    use LoggerAware;

    /**
     * @var Key|null
     */
    protected $defaultKey;

    /**
     * @var string
     */
    protected $secret;

    public function __construct($secret)
    {
        $this->secret = $secret;
    }

    /**
     * Get the default key used for encryption/decryption if no key is passed
     *
     * @return Key
     */
    public function getDefaultKey()
    {
        if (null === $this->defaultKey) {
            $secret = $this->secret;
            if (empty($secret)) {
                throw new \RuntimeException('Need an encryption secret');
            }

            try {
                $this->defaultKey = Key::loadFromAsciiSafeString($secret);
            } catch (BadFormatException $e) {

                //fallback if secret is generated by Pimcore composer plugin and is actually a byte sequence
                $secret = Encoding::saveBytesToChecksummedAsciiSafeString(
                    \Defuse\Crypto\Key::KEY_CURRENT_VERSION,
                    base64_decode($secret)
                );
                $this->defaultKey = Key::loadFromAsciiSafeString($secret);
            }
        }

        return $this->defaultKey;
    }

    /**
     * Encrypt data with key (will fall back to default key if none given)
     *
     * @param string $plaintext
     * @param bool $rawBinary
     *
     * @return string
     */
    public function encrypt($plaintext, ?Key $key = null, $rawBinary = false)
    {
        if (empty($plaintext)) {
            $this->getLogger()->warning('Returning empty encrypt() result as plaintext was empty');

            return '';
        }

        if (!$key) {
            $key = $this->getDefaultKey();
        }

        return Crypto::encrypt($plaintext, $key, $rawBinary);
    }

    /**
     * Decrypt ciphertext with key (will fall back to default key if none given)
     *
     * @param string $ciphertext
     * @param bool $rawBinary
     *
     * @return string
     */
    public function decrypt($ciphertext, ?Key $key = null, $rawBinary = false)
    {
        if (empty($ciphertext)) {
            $this->getLogger()->warning('Returning empty decrypt() result as ciphertext was empty');

            return '';
        }

        if (!$key) {
            $key = $this->getDefaultKey();
        }

        return Crypto::decrypt($ciphertext, $key, $rawBinary);
    }

    public function __sleep()
    {
        // do not serialize default key
        $this->defaultKey = null;

        return array_keys(get_object_vars($this));
    }
}
