<?php

/**
 * Pimcore
 *
 * This source file is available under two different licenses:
 * - GNU General Public License version 3 (GPLv3)
 * - Pimcore Commercial License (PCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
 *  @license    http://www.pimcore.org/license     GPLv3 and PCL
 */

namespace CustomerManagementFrameworkBundle\DataTransformer\DuplicateIndex;

use CustomerManagementFrameworkBundle\DataTransformer\DataTransformerInterface;

class Simplify implements DataTransformerInterface
{
    public function transform($data, $options = [])
    {
        return $this->simplify((string)$data);
    }

    protected function simplify($text)
    {
        return self::translit(str_replace('  ', ' ', trim(strtolower($text))));
    }

    protected function translit($text)
    {
        $search = [
            '?',
            '\'',
            '"',
            '/',
            '-',
            '+',
            '.',
            ',',
            ';',
            '(',
            ')',
            '&',
            'ä',
            'ö',
            'ü',
            'Ä',
            'Ö',
            'Ü',
            'ß',
            'É',
            'é',
            'È',
            'è',
            'Ê',
            'ê',
            'E',
            'e',
            'Ë',
            'ë',
            'À',
            'à',
            'Á',
            'á',
            'Å',
            'å',
            'a',
            'Â',
            'â',
            'Ã',
            'ã',
            'ª',
            'Æ',
            'æ',
            'C',
            'c',
            'Ç',
            'ç',
            'C',
            'c',
            'Í',
            'í',
            'Ì',
            'ì',
            'Î',
            'î',
            'Ï',
            'ï',
            'Ó',
            'ó',
            'Ò',
            'ò',
            'Ô',
            'ô',
            'º',
            'Õ',
            'õ',
            'Œ',
            'O',
            'o',
            'Ø',
            'ø',
            'Ú',
            'ú',
            'Ù',
            'ù',
            'Û',
            'û',
            'U',
            'u',
            'U',
            'u',
            'Š',
            'š',
            'S',
            's',
            'Ž',
            'ž',
            'Z',
            'z',
            'Z',
            'z',
            'L',
            'l',
            'N',
            'n',
            'Ñ',
            'ñ',
            '¡',
            '¿',
            'Ÿ',
            'ÿ',
            '_',
            ':',
        ];
        $replace = [
            '',
            '',
            '',
            '',
            '-',
            '',
            '',
            '-',
            '-',
            '',
            '',
            '',
            'ae',
            'oe',
            'ue',
            'Ae',
            'Oe',
            'Ue',
            'ss',
            'E',
            'e',
            'E',
            'e',
            'E',
            'e',
            'E',
            'e',
            'E',
            'e',
            'A',
            'a',
            'A',
            'a',
            'A',
            'a',
            'a',
            'A',
            'a',
            'A',
            'a',
            'a',
            'AE',
            'ae',
            'C',
            'c',
            'C',
            'c',
            'C',
            'c',
            'I',
            'i',
            'I',
            'i',
            'I',
            'i',
            'I',
            'i',
            'O',
            'o',
            'O',
            'o',
            'O',
            'o',
            'o',
            'O',
            'o',
            'OE',
            'O',
            'o',
            'O',
            'o',
            'U',
            'u',
            'U',
            'u',
            'U',
            'u',
            'U',
            'u',
            'U',
            'u',
            'S',
            's',
            'S',
            's',
            'Z',
            'z',
            'Z',
            'z',
            'Z',
            'z',
            'L',
            'l',
            'N',
            'n',
            'N',
            'n',
            '',
            '',
            'Y',
            'y',
            '-',
            '-',
        ];

        return str_replace($search, $replace, $text);
    }
}
