_pimcore_customermanagementframework_backend:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Admin"
    type:     attribute
    prefix:   /admin/customermanagementframework
    options:
        expose: true

_pimcore_customermanagementframework_backend_report:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Report"
    type:     attribute
    prefix:   /admin/customermanagementframework/report

_pimcore_customermanagementframework_rest:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Rest"
    type:     attribute
    prefix:   /__customermanagementframework/webservice

_pimcore_customermanagementframework_preview:
    resource: "@PimcoreCustomerManagementFrameworkBundle/Controller/Preview"
    type:     attribute
    prefix:   /__customermanagementframework



